title: Breaking Stereotypes
description: Aiming to create positive representation of people over 65 through telling visual stories
logo: /assets/images/octocat-logo.svg
show_downloads: false
theme: jekyll-theme-leap-day
