title: Breaking Stereotypes
description: The Breaking Stereotypes of the Elderly project aims to create positive representation of people over 65 through telling stories as a short film.
logo: /assets/images/octocat-logo.svg
show_downloads: false
theme: jekyll-theme-leap-day
